### ISSUE TITLE
hyposat

### ISSUE THREAD

**Issue by blazvicic** [pyrocko/contrib-snufflings#23]
hi!

i am trying to use hyposat snuffling and have some problems with it.
i think i successfully installed it.

this is the msg i get in terminal after clicking Run in hyposat snuffling (i did select phases):

```
temp dir: /tmp/hyposat-blaz-jwdjrblb
abspath /home/blaz/.snufflings/hyposat-snuffling/hyposat/bin_l/hyposat
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG
HYPOSAT output:

 HYPOSAT Version 4.4b

                                                                                


Parameters of starting solution (+/- 1 standard deviation):

No location from multiple azimuth observations found. Missing azimuth values?
Epicenter set from station  with backazimuth 315.0 [deg], delta     0. [km]
Epicenter lat:   0.7119 [deg]
Epicenter lon:  -0.7071 [deg]

Source time (set):*************** [s]
```

for the stations i use station file, for event event file, for phases phase file.

thanks!

**Comment by HerrMuellerluedenscheid** [comment]
Hey,

Could you provide me with the marker file, stations file and, if possible, some waveform snippets? You can use the "export waveforms" snuffling to cut out some example waveforms.

**Comment by blazvicic** [comment]
sure, here it is...
thanks

https://www.dropbox.com/s/x6bimsbpewrkosd/event.zip?dl=0

**Comment by HerrMuellerluedenscheid** [comment]
Did you start snuffler just like I did?
```
snuffler --stations stations --markers test_markers --events events wfs/
```
If yes, you might have stumbled into the same pitfall as I just did: There is one event marker added from the `test_markers` file and one added from the `events` file. The hyposat snuffling currently uses phase marker of the selected and _activated_ event (press `e`). However, since there are two event markers on top of each other the one obscures the other. Could you press `m` to check if there are two events? If yes, then this was probably the reason.

However, this is something that has bothered me before. I just changed the snuffling a bit to fail with a more meaningful error message. Furthermore, by default it is not necessary to have an active event when running hyposat, anymore. This can be changed by selecting the `Use active markers only` check box. I think it makes more sense this way.

To update run
```
git pull origin master
```
in your local contrib-snufflings directory. Let me know if it's working now.

**Comment by blazvicic** [comment]
yes, exactly my case... now it works, thanks!

**Comment by blazvicic** [comment]
hi!

another problem...maybe not relevant here and i should contact the dev of hyposat, but still...
on my PC with Ubuntu17.10 the hyposat works without any problems now. I am pretty sure that its running on 64bit.

now i tried to do the same on my laptop, 64bit ubuntu 16.04 and i cant compile hyposat.
when i change makefile to gfortran or fort77 and run make, this is what i get:

```
fort77 -lm -o hyposat  hyposat.o   hyposat_lib.o hyposat_geo.o hyposat_name.o hyposat_clib.o hyposat_loc.o hyposat_crust.o hyposat_crust_mod.o hyposat_mag.o hyposat_cross.o hyposat_time.o hyposat_gmi.o hyposat_file.o libtau_h.o  
/usr/bin/ld: i386 architecture of input file `hyposat.o' is incompatible with i386:x86-64 output
/usr/bin/ld: i386 architecture of input file `hyposat_lib.o' is incompatible with i386:x86-64 output
/usr/bin/ld: i386 architecture of input file `hyposat_geo.o' is incompatible with i386:x86-64 output
/usr/bin/ld: i386 architecture of input file `hyposat_name.o' is incompatible with i386:x86-64 output
/usr/bin/ld: i386 architecture of input file `hyposat_clib.o' is incompatible with i386:x86-64 output
/usr/bin/ld: i386 architecture of input file `hyposat_loc.o' is incompatible with i386:x86-64 output
/usr/bin/ld: i386 architecture of input file `hyposat_crust.o' is incompatible with i386:x86-64 output
/usr/bin/ld: i386 architecture of input file `hyposat_crust_mod.o' is incompatible with i386:x86-64 output
/usr/bin/ld: i386 architecture of input file `hyposat_mag.o' is incompatible with i386:x86-64 output
/usr/bin/ld: i386 architecture of input file `hyposat_cross.o' is incompatible with i386:x86-64 output
/usr/bin/ld: i386 architecture of input file `hyposat_time.o' is incompatible with i386:x86-64 output
/usr/bin/ld: i386 architecture of input file `hyposat_gmi.o' is incompatible with i386:x86-64 output
/usr/bin/ld: i386 architecture of input file `hyposat_file.o' is incompatible with i386:x86-64 output
/usr/bin/ld: i386 architecture of input file `libtau_h.o' is incompatible with i386:x86-64 output
hyposat_file.o: In function `file_check__':
hyposat_file.f:(.text+0xd5): undefined reference to `G77_getenv_0'
libtau_h.o: In function `depcor_':
libtau_h.f:(.text+0x1779): undefined reference to `G77_abort_0'
libtau_h.o: In function `__g77_masterfun_umod':
libtau_h.f:(.text+0x3c4f): undefined reference to `G77_abort_0'
collect2: error: ld returned 1 exit status
mv hyposat ../bin_l/hyposat
mv: cannot stat 'hyposat': No such file or directory
Makefile:41: recipe for target 'hyposat' failed
make: *** [hyposat] Error 1


```

any idea? i mean, i guess the problem is 32 64, but why was it working on my pc but not laptop?

thakns!

**Comment by HerrMuellerluedenscheid** [comment]
I'm afraid I can't come up with an answer to that one. Maybe you have to
set a linking flag to fix this. Did you try to download the hyposat source
code from the norsar ftp server? There are some precompiled versions
available. Maybe one of those works out of the box.
Other hints @emolch @miili?

2017-11-30 19:13 GMT+01:00 blazvicic <notifications@github.com>:

**Comment by blazvicic** [comment]
solved ...
what i was doing now was that i downloaded the tar of hyposat from ftp and try to compile it - it did not work (on my PC it did).

but it does work if i just clone the git and run setup.py. 

thanks for the not so obvious tip :)

**Comment by HerrMuellerluedenscheid** [comment]
Cool! I'm glad it works that way!

Am 30.11.2017 8:09 nachm. schrieb "blazvicic" <notifications@github.com>:

solved ...
what i was doing now was that i downloaded the tar of hyposat from ftp and
try to compile it - it did not work (on my PC it did).

but it does work if i just clone the git and run setup.py.

thanks for the not so obvious tip :)

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/pyrocko/contrib-snufflings/issues/23#issuecomment-348289392>,
or mute the thread

**Comment by emolch** [comment]
The errors

```
/usr/bin/ld: i386 architecture of input file `hyposat_name.o' is incompatible with i386:x86-64 output
/usr/bin/ld: i386 architecture of input file `hyposat_clib.o' is incompatible with i386:x86-64 output
/usr/bin/ld: i386 architecture of input file `hyposat_loc.o' is incompatible with i386:x86-64 output
```

look like there were still some object files compiled on a different machine lying around in the src dir. Did you run `make clean` before `make`?

**Comment by blazvicic** [comment]
i did, that was the first thing that i thought of ...

make: *** No rule to make target 'clean'.  Stop.

**Comment by HerrMuellerluedenscheid** [comment]
I added a 'clean' to the makefile yesterday evening. You probably have to
pull an update again.

Am 01.12.2017 9:38 vorm. schrieb "blazvicic" <notifications@github.com>:

**Comment by blazvicic** [comment]
well in any case it works now. i dont want to break the install now, since i need this tool :)
